### ISSUE TITLE
Does DT 6.2 supports Dynatrace-GenericOperations-Plugin ?

### ISSUE THREAD

**Issue by jalpeshshelar** [Dynatrace/Dynatrace-GenericOperations-Plugin#1]
Hi ,

We are using DT 6.2.
We have tried to make changes in plugin but it's not working.

Please make it available for DT 6.2.

Thanks & Regards,
Jalpesh

**Comment by josecolella** [comment]
@jalpeshshelar Dynatrace 6.2 will be end of life this december. This plugin utilizes stream for Java 8, and thus why Dynatrace 6.2 is not supported, and will not be supported.
