### ISSUE TITLE
Can this work with one of the measures as a static value?

### ISSUE THREAD

**Issue by ghost** [Dynatrace/Dynatrace-GenericOperations-Plugin#2]
Does this plugin support static values? eg. Measure one + measure two where measure two is always 10300?

**Comment by josecolella** [comment]
@Dynatrace-Adam-Gardner It is in the roadmap. Will keep you up to date when the feature is added.

**Comment by ghost** [comment]
Hi Jose, think this might be it. Only bug I can see if if I add the same measure name and set one to a different aggregation (eg. count)... The plugin doesn't currently have logic to figure out which to add.

[IPlanetMonitorV2.java.txt](https://github.com/Dynatrace/Dynatrace-GenericOperations-Plugin/files/651956/IPlanetMonitorV2.java.txt)

**Comment by josecolella** [comment]
Dude @Dynatrace-Adam-Gardner this is great. Do you have time to create a pull request?

**Comment by ghost** [comment]
Done. The plugin needs two new boolean variables - whether or not each measure is static ("first_measure_static_bool" and "second_measure_static_bool"). I have only edited the IPlanetMonitor file with the pull request so the GUI will need to be updated.

**Comment by Dynatrace-Kyle-Kowalski** [comment]
@Dynatrace-Adam-Gardner For using a static value, I'm creating a dashboard with 1 measure on it and instead of pointing to the name of the measure I can just put the number there ie: Measure 1= MyResponseTimeMeasure, Measure 2 = 250 so this will do an operation with the first measure and the number value?

**Comment by ghost** [comment]
Yes. Let's assume **MyResponseTimeMeasure** came out to be 140. So the calculation would be 140/250. **result = 0.56**

**Comment by josecolella** [comment]
GUI has been updated. Pull requests have been merged. Thanks @Dynatrace-Adam-Gardner. You are a beast

**Comment by Dynatrace-Kyle-Kowalski** [comment]
Just a heads up the jar in the build folder is still using the old version.
