### ISSUE TITLE
New build for bug fixes

### ISSUE THREAD

**Issue by josecolella** [Dynatrace/Dynatrace-GenericOperations-Plugin#8]
Hey @Dynatrace-Adam-Gardner  and @Dynatrace-Kyle-Kowalski ,
After having the pull request merged, can you guys create the .jar and make a new release?

**Comment by Dynatrace-Kyle-Kowalski** [comment]
Yeah I'll do that later today.

On Feb 28, 2017, at 7:58 AM, Jose Miguel Colella <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey @Dynatrace-Adam-Gardner<https://github.com/Dynatrace-Adam-Gardner> and @Dynatrace-Kyle-Kowalski<https://github.com/Dynatrace-Kyle-Kowalski> ,
After having the pull request merged, can you guys create the .jar and make a new release?

**Comment by Dynatrace-Kyle-Kowalski** [comment]
Release posted on community, this issue can be closed

**Comment by ingohackl** [comment]
I have created a release on GitHub and linked to it from the community page. 
We can only track downloads on GitHub therefore it's important to create the release on GitHub.

**Comment by josecolella** [comment]
Great. Thanks @ingohackl and @Dynatrace-Kyle-Kowalski
